version: '3'

services:

  rabbitmq-node1:
    image: rabbitmq:3.13.2-management
    container_name: rabbitmq-node1
    hostname: rabbitmq-node1
    entrypoint: /bin/bash -c "rabbitmq-server rabbitmqctl wait /var/lib/rabbitmq/mnesia/rabbit@rabbitmq-node1.pid"
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./rabbitmq_delayed_message_exchange-3.13.0.ez:/plugins/rabbitmq_delayed_message_exchange-3.13.0.ez
      - ./.erlang.cookie:/var/lib/rabbitmq/.erlang.cookie
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    environment:
      - RABBITMQ_DELAYED_MESSAGE_ENABLED=true
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=66mIBXeUUOloL0tcFmnqJOllantFRedAMDvcpqP8
      - RABBITMQ_PLUGINS=--offline rabbitmq_delayed_message_exchange
      - RABBITMQ_NODENAME=rabbit@rabbitmq-node1
    networks:
      - rabbitmq-network
      
  # rabbitmq-node2:
  #   image: rabbitmq:3.13.2-management
  #   container_name: rabbitmq-node2
  #   hostname: rabbitmq-node2
  #   entrypoint: /bin/bash -c "rabbitmq-server rabbitmqctl wait /var/lib/rabbitmq/mnesia/rabbit@rabbitmq-node2.pid && rabbitmqctl join_cluster rabbit@rabbitmq-node1"
  #   ports:
  #     - "5673:5672"
  #     - "15673:15672"
  #   volumes:
  #     - ./rabbitmq_delayed_message_exchange-3.13.0.ez:/plugins/rabbitmq_delayed_message_exchange-3.13.0.ez
  #     - ./.erlang.cookie:/var/lib/rabbitmq/.erlang.cookie
  #     - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
  #   environment:
  #     - RABBITMQ_DELAYED_MESSAGE_ENABLED=true
  #     - RABBITMQ_DEFAULT_USER=admin
  #     - RABBITMQ_DEFAULT_PASS=66mIBXeUUOloL0tcFmnqJOllantFRedAMDvcpqP8
  #     - RABBITMQ_PLUGINS=--offline rabbitmq_delayed_message_exchange
  #     - RABBITMQ_NODENAME=rabbit@rabbitmq-node2
  #   networks:
  #     - rabbitmq-network
  #   depends_on:
  #     - rabbitmq-node1
      
  # rabbitmq-node3:
  #   image: rabbitmq:3.13.2-management
  #   container_name: rabbitmq-node3
  #   hostname: rabbitmq-node3
  #   entrypoint: /bin/bash -c "rabbitmq-server rabbitmqctl wait /var/lib/rabbitmq/mnesia/rabbit@rabbitmq-node3.pid && rabbitmqctl join_cluster rabbit@rabbitmq-node1"
  #   ports:
  #     - "5674:5672"
  #     - "15674:15672"
  #   volumes:
  #     - ./rabbitmq_delayed_message_exchange-3.13.0.ez:/plugins/rabbitmq_delayed_message_exchange-3.13.0.ez
  #     - ./.erlang.cookie:/var/lib/rabbitmq/.erlang.cookie
  #     - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
  #   environment:
  #     - RABBITMQ_DELAYED_MESSAGE_ENABLED=true
  #     - RABBITMQ_DEFAULT_USER=admin
  #     - RABBITMQ_DEFAULT_PASS=66mIBXeUUOloL0tcFmnqJOllantFRedAMDvcpqP8
  #     - RABBITMQ_PLUGINS=--offline rabbitmq_delayed_message_exchange
  #     - RABBITMQ_NODENAME=rabbit@rabbitmq-node3
  #   networks:
  #     - rabbitmq-network
  #   depends_on:
  #     - rabbitmq-node1
      
networks:
  rabbitmq-network:
    driver: bridge
